apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-canneal
  labels:
    name: parsec-canneal
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_canneal
        name: parsec-canneal
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 0-1 ./run -a run -S parsec -p canneal -i native -n 8"]
        resources:
          requests:
            memory: "15Gi"
            cpu: "1800m"
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-b-4core"

---

apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-blackscholes
  labels:
    name: parsec-blackscholes
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_blackscholes
        name: parsec-blackscholes
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 2-3 ./run -a run -S parsec -p blackscholes -i native -n 8"]
        resources:
          requests:
            memory: "15Gi"
            cpu: "1800m"
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-b-4core"
