
apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-freqmine
  labels:
    name: parsec-freqmine
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_freqmine
        name: parsec-freqmine
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 0-3 ./run -a run -S parsec -p freqmine -i native -n 8"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-b-4core"

---

apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-vips
  labels:
    name: parsec-vips
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_vips
        name: parsec-vips
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 0-3 ./run -a run -S parsec -p vips -i native -n 4"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-b-4core"