apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-ferret
  labels:
    name: parsec-ferret
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_ferret
        name: parsec-ferret
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "for i in 1 2 4 8; do ./run -a run -S parsec -p ferret -i native -n $i; sleep 10; done"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "parsec"
